Repository PolSl-PBL-7/DragonEye, pull requests merged in 2021-11, with the labels that each got.

#4 feat: added pr template
  .drone.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement, ci-failing

#6 feat(scripts): windows depes installation and profile
  .gitignore
  README.md
  scripts/install.ps1
  scripts/profile.ps1
Labels: enhancement, ci-failing

#7 PBL-75 feat(models): initial version of ChongTay model blocks
  .drone.yml
  .flake8
  .mypy.ini
  Dockerfile
  Makefile
  Pipfile
  Pipfile.lock
  dnn/models/conv/__init__.py
  dnn/models/conv/blocks.py
  dnn/models/full_models/spatiotemporal_autoencoder.py
  dnn/test/test_bottleneck.py
  dnn/test/test_decoder.py
  dnn/test/test_encoder.py
  dnn/test/test_spatiotemporal_autoencoder.py
  macos.depends
  scripts/hack.sh
  scripts/install-non-depends.sh
  scripts/replace.sh
  utils/iteration_utils.py
  utils/test/test_iteration_utils.py
Labels: enhancement

#10 feat: moved to requirements.txt and created bootstrapper
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/library-scripts/common-debian.sh
  .devcontainer/library-scripts/python-debian.sh
  .drone.yml
  .flake8
  .gitignore
  .vscode/extensions.json
  CONTRIBUTING.md
  Dockerfile
  Dockerfile.CI
  Makefile
  Pipfile
  Pipfile.lock
  README.md
  __init__.py
  data/__init__.py
  data/processing/__init__.py
  data/processing/component.py
  data/processing/process.py
  data/processing/sinks.py
  data/processing/source.py
  data/tests/processing/test_data_processing.py
  data/tests/processing/test_processor.py
  data/tests/versioning/setup.py
  data/versioning/configs.py
  data/versioning/handler.py
  docs/resources/docker-settings.png
  macos.depends
  requirements.txt
  scripts/bootstrap.py
  scripts/bootstrap.sh
  scripts/bootstrap.toml
  scripts/hack.sh
  scripts/install-cuda.sh
  scripts/install-non-depends.sh
  scripts/install.ps1
  scripts/profile.ps1
  scripts/replace.sh
Labels: documentation, enhancement
